export default {
  theme: {
    extend: {
      colors: {
        'surface': '#000000',
        'surface-dim': '#050505',
        'surface-bright': '#18181B',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#09090B',
        'surface-container': '#121212',
        'surface-container-high': '#1C1C1C',
        'surface-container-highest': '#272727',
        'on-surface': '#FFFFFF',
        'on-surface-variant': '#A1A1AA',
        'primary': '#FFFFFF',
        'on-primary': '#000000',
        'primary-container': '#27272A',
        'on-primary-container': '#FFFFFF',
        'secondary': '#E4E4E7',
        'on-secondary': '#000000',
        'secondary-container': '#3F3F46',
        'on-secondary-container': '#FFFFFF',
        'tertiary': '#FFFFFF',
        'on-tertiary': '#000000',
        'outline': '#27272A',
        'outline-variant': '#18181B',
        'background': '#000000',
        'on-background': '#FFFFFF',
        'success': '#22C55E',
        'error': '#EF4444',
        'warning': '#F59E0B',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-sm': ['Inter', 'sans-serif'],
        'data-mono': ['Roboto Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400', letterSpacing: '0' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'display-sm': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.02em' }],
        'data-mono': ['12px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '-0.01em' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '0' }],
        'label-caps': ['11px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em', textTransform: 'uppercase' }],
      },
      spacing: {
        'unit': '4px',
        'gutter': '1px',
        'panel-sidebar': '240px',
        'container-padding': '1.5rem',
        'stack-md': '16px',
        'stack-xs': '4px',
        'stack-sm': '8px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
